### ISSUE TITLE
Cài đặt và sử dụng trên giao diện dòng lệnh

### ISSUE THREAD

**Issue by Vunb** [Vunb/vntk#1]
Cài đặt `vntk` sử dụng `npm`:

`npm install -g vntk`

Sau đó, chạy một tiện ích trong vntk, ví dụ cho bài toán tách từ tiếng Việt (word segmentation) như sau:

# Xử lý input là một chuỗi
Input: `vntk ws "Chào mừng bạn đến với đất nước Việt Nam"`
Output: `Chào_mừng bạn đến với đất_nước Việt_Nam`

# Xử lý input là một tệp tin
Input: `vntk ws -f demo.txt another.txt`
Output: `demo.txt.seg`, `another.txt.seg`

# Xử lý như một thư viện
```javascript
var vntk = require("vntk");

vntk.ws("Chào mừng bạn đến với đất nước Việt Nam");
// Output: Chào_mừng bạn đến với đất_nước Việt_Nam
```

**Comment by vanquyenbkhn** [comment]
Gói vntk tự cho phép tách từ luôn ah a

**Comment by Vunb** [comment]
Đúng rồi e
