### ISSUE TITLE
A vntk-based chatbot framework

### ISSUE THREAD

**Issue by vunb** [vunb/vntk#21]
From the article: **[The commercial NLP landscape in 2017][1]**

> Gartner views conversational systems as one of the top ten strategic technology
trends for 2017 and predicts that, by 2020, the average person will have more
conversations with bots than with their spouse.

So, It is great if we have an industry-chatbot framework for English and Vietnamese? See vntk/chatbot#1

[1]: https://www.cambridge.org/core/services/aop-cambridge-core/content/view/CDCE7C93C48CFDF9094908F3A0DB9E26/S1351324917000237a.pdf/commercial_nlp_landscape_in_2017.pdf

**Comment by zeloru** [comment]
Anh tham khảo 2 thằng sau:

https://github.com/Yoctol/bottender

https://github.com/claudiajs/claudia-bot-builder

Em chỉ dùng facebook nên dùng bootbot.

**Comment by vunb** [comment]
@zeloru `bootbot` khá đơn giản và tiện lợi 👍 quan trọng nhất trước tiên có lẽ là dựng khung engine trước, việc tích hợp interface nào a sẽ tham khảo thêm. 1 vote cho facebook + skype 😄

**Comment by hungvmcio** [comment]
Trân trọng cảm ơn!

**Comment by hungvmcio** [comment]
Trân trọng cảm ơn!

**Comment by vunb** [comment]
The alpha version has released and merged 

Please check it out:

* Installation guide & source code:  https://github.com/vntk/vntk-chatbot-framework
* Merged requests https://github.com/vntk/vntk-chatbot-framework/pull/2
* Chat room: https://gitter.im/vntk/vntk-chatbot-framework

It is in early stage. Hope you enjoy and make it better.
Thanks!

**Comment by chukimthoa1994** [comment]
em mới tìm hiểu vntk, em muốn hỏi 1 chút, xây dựng cdsl để train ntn ạ

**Comment by vunb** [comment]
Please follow the project @yeuai.

* Framework https://github.com/yeuai/rivebot-ce
* BotScript engine: https://github.com/yeuai/botscript

Experimental platform: https://botscript.ai
