### ISSUE TITLE
vntk not support linux

### ISSUE THREAD

**Issue by khanhoatink4** [vunb/vntk#22]
i installed vntk on linux, but not support
error: node_modules/crfsuite/lib/binding/crfsuite.node: invalid ELF header

**Comment by vunb** [comment]
Hi @khanhoatink4 
Please try install vntk with option: **npm i vntk --update-binary**
If it does not work, tell me what type of linux OS do you use ?

**Comment by khanhoatink4** [comment]
Thanks very much!, it worked!
