### ISSUE TITLE
Lỗi cài vntk-master

### ISSUE THREAD

**Issue by hungvmcio** [vunb/vntk#24]
Dear bạn!
Hiện tại mình download module vntk-master và sau đó chạy npm install để cài đặt các module còn thiếu
tuy nhiên khi cài lệnh xong đang báo lỗi 
"node-pre-gyp ERR! Tried to download(404): https://github.com/vunb/node-crfsuite/releases/download/0.9.3/crfsuite-v0.9.3-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for crfsuite@0.9.3 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp)"

qua kiểm tra link https://github.com/vunb/node-crfsuite/releases/download/0.9.3/crfsuite-v0.9.3-node-v59-win32-x64.tar.gz thì không tồn tại.

Bạn kiểm tra lại nhé.

**Comment by vunb** [comment]
Chào bạn,

Bạn đang dùng `node 9` đúng không? Hiện mình mới hỗ trợ pre-built cho các phiên bản node 4, 5, 6, 7, 8. Chưa có cho node 9, bạn có thể cài đặt dùng lệnh sau với tham số `--build-from-source`:

> npm install --build-from-source

Bạn thử xem ok không nhé? Thời gian tới mình sẽ build thêm cho node 9 sau 😄 .

**Comment by hungvmcio** [comment]
Dear bạn!
Sau khi thực hiện theo hướng dẫn của bạn thì lỗi như dưới
Mình đang dùng windows 10

[error.txt](https://github.com/vunb/vntk/files/1523555/error.txt)

**Comment by vunb** [comment]
Mình build thử trên Windows bản 32, 64bit đều thành công. Bạn chờ để mình cập nhật bản pre-build cho nodejs 9 nhé :)

https://ci.appveyor.com/project/Vunb/node-crfsuite

**Comment by HUYNHVINH2** [comment]
anh ơi buil cho node v-9 trở lên với a ơi e đang sd node v 10.15

**Comment by vunb** [comment]
@HUYNHVINH2 em có thể add thêm cấu hình cho node 10 và tạo PULL request ko? Ngay lúc này a chưa có thời gian làm ngay đc.

**Comment by HUYNHVINH2** [comment]
Vâng em cảm ơn anh ạ !


Vào Th 5, 11 thg 4, 2019 vào lúc 13:53 Vu Bao Nhu <
notifications@github.com> đã viết:
