### ISSUE TITLE
Thêm api lấy dữ liệu Tiếng Việt từ Concept5 

### ISSUE THREAD

**Issue by zeloru** [vunb/vntk#32]
Tham khảo: http://conceptnet.io/

ConceptNet is a freely-available semantic network, designed to help computers understand the meanings of words that people use.

ConceptNet is used to create word embeddings -- representations of word meanings as vectors, similar to word2vec, GloVe, or fastText, but **better**. https://github.com/commonsense/conceptnet-numberbatch

**Comment by vunb** [comment]
Not necessarily! Feel free to re-open with more attractive reason.
