### ISSUE TITLE
Làm thế nào để build new model?

### ISSUE THREAD

**Issue by trumhemcut** [vunb/vntk#41]
Cho anh hỏi ngu xíu là anh muốn build new model, anh thấy có các file model.bin á. Thì mình cần làm ntn?

**Comment by vunb** [comment]
Hi a @trumhemcut 

Anh có thể dùng bộ training của [Underthesea](https://github.com/magizbox/underthesea) để build các model này. Vntk tương thích và sử dụng được.

Ngoài ra, em có viết bộ **tagger** riêng cho Vntk nhưng chưa hoàn thiện. Nhưng a có thể tham khảo tại đây [vntk/vntk-tagger](https://github.com/vntk/vntk-tagger).

**Comment by vunb** [comment]
Closing due to inactitivity.
