### ISSUE TITLE
lỗi không install được

### ISSUE THREAD

**Issue by ldragon2512** [vunb/vntk#42]
`Last login: Sun Jul 29 21:46:46 on ttys002
LDragons-MacBook-Pro:~ Ldragon$ npm install -g vntk

> fasttext@0.2.3 preinstall /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/fasttext
> npm install node-pre-gyp

/Users/Ldragon/.npm-global/bin/node-pre-gyp -> /Users/Ldragon/.npm-global/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
+ node-pre-gyp@0.10.3
updated 1 package in 54.546s

> crfsuite@0.9.4 preinstall /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite
> npm install node-pre-gyp

/Users/Ldragon/.npm-global/bin/node-pre-gyp -> /Users/Ldragon/.npm-global/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
+ node-pre-gyp@0.10.3
updated 1 package in 1.503s
/Users/Ldragon/.npm-global/bin/vntk -> /Users/Ldragon/.npm-global/lib/node_modules/vntk/bin/vntk.js

> crfsuite@0.9.4 postinstall /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/vunb/node-crfsuite/releases/download/0.9.4/crfsuite-v0.9.4-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for crfsuite@0.9.4 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/vunb/node-crfsuite/releases/download/0.9.4/crfsuite-v0.9.4-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for crfsuite@0.9.4 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/crfsuite/liblbfgs/lib/lbfgs.o
  CC(target) Release/obj.target/crfsuite/liblbfgs/lib/lbfgs.o
rm: ./Release/.deps/Release/obj.target/crfsuite/liblbfgs/lib/lbfgs.o.d.raw: No such file or directory
make: *** [Release/obj.target/crfsuite/liblbfgs/lib/lbfgs.o] Error 1
gyp ERR!  CC(target) Release/obj.target/crfsuite/crfsuite/lib/crf/src/crf1d_context.o
 build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding/crfsuite.node" "--module_name=crfsuite" "--module_path=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding"
gyp ERR! cwd /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding/crfsuite.node --module_name=crfsuite --module_path=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding/crfsuite.node --module_name=crfsuite --module_path=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding' (1)
../crfsuite/lib/crf/src/crf1d_context.c:71:17: warning: using the result of an assignment as a condition without parentheses
      [-Wparentheses]
        if (ret = crf1dc_set_num_items(ctx, T)) {
            ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../crfsuite/lib/crf/src/crf1d_context.c:71:17: note: place parentheses around the assignment to silence this warning
        if (ret = crf1dc_set_num_items(ctx, T)) {
                ^
            (                                 )
../crfsuite/lib/crf/src/crf1d_context.c:71:17: note: use '==' to turn this assignment into an equality comparison
        if (ret = crf1dc_set_num_items(ctx, T)) {
                ^
                ==
../crfsuite/lib/crf/src/crf1d_context.c:440:15: warning: unused variable 'L' [-Wunused-variable]
    const int L = ctx->num_labels;
              ^
../crfsuite/lib/crf/src/crf1d_context.c:438:38: warning: unused variable 'cur' [-Wunused-variable]
    const floatval_t *state = NULL, *cur = NULL, *trans = NULL;
                                     ^
3 warnings generated.⠙ postinstall: info lifecycle crfsuite@0.9.4~postinstall: Failed to exec postinstall script
make: *** No rule to make target `../crfsuite/lib/crf/src/crf1d_encode.c', needed by `Release/obj.target/crfsuite/crfsuite/lib/crf/src/crf1d_encode.o'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding/crfsuite.node" "--module_name=crfsuite" "--module_path=/Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite/lib/binding"
gyp ERR! cwd /Users/Ldragon/.npm-global/lib/node_modules/vntk/node_modules/crfsuite
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crfsuite@0.9.4 postinstall: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crfsuite@0.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Ldragon/.npm/_logs/2018-07-29T15_52_38_147Z-debug.log
LDragons-MacBook-Pro:~ Ldragon$ `

**Comment by ldragon2512** [comment]
đã thử dùng sudo nhưng vẫn không được :(

**Comment by vunb** [comment]
Hi @ldragon2512 

Hiện bản Node 10 chưa ready nên mình chưa test và có chưa có bản pre-build cho nó.
Bạn có thể cài đặt lại nodejs xuống phiên bản thấp hơn ko?
Recommend bạn nên cài bản NodeJS 8 LTS.

Mình sẽ test và hỗ trợ NodeJS 10 trong thời gian sắp tới.

**Comment by ldragon2512** [comment]
@vunb tks bạn nhiều nhé ;) đã fix đc
