### ISSUE TITLE
CÀI ĐẶT BỊ LỖI

### ISSUE THREAD

**Issue by trangchan1234** [vunb/vntk#49]
Em xin chào,
Em không biết tẹo nào về code cả chỉ vô tình rơi vào hoàn cảnh phải phân tích nlp tiếng việt.
Em mới cài đặt cái này nhưng bị lỗi, cho em hỏi: "Có phải vntk này chỉ chạy trên linux ko ạ? Vì em đang sài window k muốn dùng linux"
Em mong được các cao thủ giải đáp giúp.
Em cảm ơn ạ.

**Comment by vunb** [comment]
Chào @trangchan1234 
Vntk hỗ trợ cả Windows bạn nhé. Bạn gặp lỗi gì và dùng phiên bản `NodeJS` bao nhiêu?

**Comment by trangchan1234** [comment]
dạ, nodejs 12.16.2
lỗi đây ạ:
![Capture](https://user-images.githubusercontent.com/63952203/79713256-7afaa100-82f7-11ea-83c0-5e2f2c13d5bb.PNG)

**Comment by vunb** [comment]
Có thấy dòng nào báo lỗi đâu bạn? Như hình bạn gửi là cài đặt thành công rồi đó! Nhưng nó cảnh báo bạn chú ý, chưa khởi tạo dự án mà đã cài đặt thư viện rồi.

Đây là kiến thức căn bản khi bạn bước chân vào lập trình. Bạn cần phải khởi tạo dự án đầu tiên và sau đó viết 1 chương trình `Hello World` kinh điển mà ai cũng phải làm.

Nếu chưa biết NodeJS là gì và chưa biết khởi tạo dự án Node như thế nào thì bạn tìm hướng dẫn trên Google, hoặc tham gia vào diễn đàn https://nodejs.vn hoặc join nhóm Facebook Group, mọi người sẽ giúp đỡ cho bạn thêm nhé.

* Diễn đàn: https://nodejs.vn/
* FB Group: https://www.facebook.com/groups/congdong.nodejs.vietnam/

**Comment by trangchan1234** [comment]
dạ vâng. Hì em cảm ơn ạ.
Là em thiếu kiến thức thiệt

**Comment by vunb** [comment]
Trong quá trình sử dụng bạn gặp vấn đề gì cứ gửi báo lỗi lên nhé. Mình sẽ cố gắng hỗ trợ!

Mình sẽ đóng issue này lại, vì không liên quan tới lỗi thư viện.
