### ISSUE TITLE
Crawl dữ liệu từ FB sử dụng graph API

### ISSUE THREAD

**Issue by vanquyenbkhn** [vunb/vntk#5]
GraphAPI trên facebook cho phép lấy dữ liệu theo định dạng json.
![image](https://cloud.githubusercontent.com/assets/14557921/18296677/80b47ba4-74d5-11e6-90ca-1d33d6433241.png)
Tuy nhiên input đầu vào của chương trình chatbot cần là những đoạn hội thoại liền kế nhau.
Input.txt:
"Đừng lo em ơi. Đi học hay k k còn quan trọng nữa. Đơn giản chỉ là cái \"tha thu\" mà sơn tùng vẽ lên thôi"
"Không hiểu sao nói từ bà già với mẹ mình éo nói được chứ =-= mà nhiều đứa nói hồn nhiên vãi"

=> mục tiêu: viết 1 tool bằng java/php sử dụng SDK facebook cho phép crawl dữ liệu từ 1 trang fb (lấy comment) và lưu vào file input.txt

**Comment by joehua87** [comment]
@vanquyenbkhn không parse json ra text được hả bạn?

**Comment by nicksmd** [comment]
Sao ko viết luôn bằng nodejs ạ?

**Comment by vunb** [comment]
Lack of activity 🔥
