### ISSUE TITLE
can not run vntk function (tag) in parallel.

### ISSUE THREAD

**Issue by khacduylam** [vunb/vntk#54]
Thank you for this module, it helped me so much for my work. But there have a problem with me, I can not run multi vntk.workTokenizer().tag at the same time (Promise.all). I tried to use `promisify` on the function but it did not work for me. Please give me a solution about it...

**Comment by vunb** [comment]
Hello,
Currently, VNTK did not implemented async mode for labeling NLP tasks. The async mode can be archived by module [node-crfsuite](https://github.com/vunb/node-crfsuite).

So, to run in parallel with vntk you can use [Workers](https://nodejs.org/api/worker_threads.html) module which is supported in nodejs!

Ref: https://nodejs.org/api/worker_threads.html

**Comment by vunb** [comment]
Please re-open the issue if you still need a help!
